import React from 'react';
import { FileText, RefreshCw } from 'lucide-react';
import { Card, PageHeader, Loading, ErrorState, Alert } from '../ui/UI';
import { ReportsTable } from '../prediction/Tables';

export default function PatientReports({ onNavigate, reports, reload }) {
  return (
    <div className="stack-lg">
      <PageHeader
        title="Medical Reports"
        subtitle="PDF reports generated by the server for your saved predictions."
        actions={<button className="btn btn-ghost" onClick={reload}><RefreshCw /> Refresh</button>}
      />
      <Alert type="info">
        To create a new report, open a prediction under <button className="link" onClick={() => onNavigate('/patient/result')}>Results</button> and
        choose <b>Generate PDF Report</b>.
      </Alert>
      <Card title="My reports" icon={FileText} noBody>
        {reports.loading ? <Loading /> : reports.error ? <ErrorState message={reports.error} onRetry={reload} /> : (
          <ReportsTable reports={reports.list} onViewPrediction={(id) => onNavigate(`/patient/result/${id}`)} />
        )}
      </Card>
    </div>
  );
}
